favicon: null
name: 'Z21, Lean Product Management on Demand'
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#27390D'
    - '#9AB44B'
    - '#F3F94C'
    - '#E8EAD0'
    - '#92C6FD'
  lightness: 0
typography_spectrum: 0.49443
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2819549
analytics:
  twitter: null
  google: UA-74091752-1
  facebook: null
