name: z21
favicon: null
layout_spectrum: 0.8357587971258909
typography_spectrum: 0.9471303129103035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10838287184014916
  lightness: 0.4710935652256012
  saturation: 0.15901613258756697
  rhythmicContrast: 0.7547214811202139
purpose: []
