name: 'Z21, Lean Product Management on Demand'
favicon: null
layout_spectrum: 0.596217
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74091752-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27390D'
    - '#9AB44B'
    - '#F3F94C'
    - '#E8EAD0'
    - '#92C6FD'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5193341
purpose: []
