analytics:
  google: UA-74091752-1
color:
  brandColors:
    - '#ffffff'
    - '#f1404b'
    - '#252c41'
    - '#848894'
    - '#fabdc1'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.596217
name: 'Z21, Catalyzing Innovation'
opengraph: {}
purpose: []
typography_spectrum: 0.75743
