name: 'Z21, Catalyzing Innovation'
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: 'Z21 LLC, Catalyzing Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#898989'
    - '#000000'
    - '#fcfcfc'
    - '#323232'
    - '#c7c7c7'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
