name: 'Z21, Catalyzing Innovation'
favicon: null
layout_spectrum: 0.25929
typography_spectrum: 0.99907
title: 'Z21 LLC, Catalyzing Innovation'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74091752-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f1404b'
    - '#252c41'
    - '#848894'
    - '#fabdc1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
