name: 'Z21, Catalyzing Innovation'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24257
title: 'Z21 LLC, Catalyzing Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#8f8f8f'
    - '#f0f0f0'
    - '#bdbdbd'
    - '#3d3d3d'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
